CREATE TABLE Customer(
	CustomerID INT PRIMARY KEY IDENTITY(1,1),
	CustomerName VARCHAR(50),
	CustomerEmail VARCHAR(50),
	CustomerPassword VARCHAR(50),
	CustomerGender VARCHAR(6),
	CustomerAddress VARCHAR(50),
	CustomerRole VARCHAR(5)
);

CREATE TABLE Artist(
	ArtistID INT PRIMARY KEY IDENTITY(1,1),
	ArtistName VARCHAR(50),
	ArtistImage VARCHAR(50)
);

CREATE TABLE Album(
	AlbumID INT PRIMARY KEY IDENTITY(1,1),
	ArtistID INT NOT NULL,
	AlbumName VARCHAR(50),
	AlbumImage VARCHAR(50),
	AlbumPrice VARCHAR(50),
	AlbumStock VARCHAR(50),
	AlbumDescription VARCHAR(50),
	FOREIGN KEY (ArtistID) REFERENCES Artist(ArtistID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE TransactionHeader(
	TransactionID INT PRIMARY KEY IDENTITY(1,1),
	TransactionDate DATE,
	CustomerID INT NOT NULL,
	FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE TransactionDetail(
	TransactionID INT NOT NULL,
	AlbumID INT NOT NULL,
	Qty INT,
	FOREIGN KEY (TransactionID) REFERENCES TransactionHeader(TransactionID) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (AlbumID) REFERENCES Album(AlbumID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Cart(
	CustomerID INT NOT NULL,
	AlbumID INT NOT NULL,
	Qty INT,
	FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (AlbumID) REFERENCES Album(AlbumID) ON UPDATE CASCADE ON DELETE CASCADE
);